controller:
  service:
    targetPorts:
      http: http
      https: http
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '60'
#      external-dns.alpha.kubernetes.io/hostname: ${hostname}.
  publishService:
    enabled: true

  config:
    server-tokens: "false"
    use-forwarded-headers: "true"
    set-real-ip-from: "${proxy_real_ip_cidr}"

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  podAnnotations:
    co.elastic.logs/module: nginx
    co.elastic.logs/fileset.stdout: ingress_controller
    co.elastic.logs/fileset.stderr: error

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: eks.amazonaws.com/capacityType
            operator: In
            values:
              - ON_DEMAND

rbac:
  create: true
